# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] #node.js version 14 reicht zum testen oder?

    steps:
      - uses: actions/checkout@mv2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./montagsmaler-frontend
        run: npm install
      - name: Run tests
        uses: ahmedrizwan/angular-karma-test-action
        working-directory: ./montagsmaler-frontend
        run: npm test
